### ISSUE TITLE
Unable to add steps to Test plan

### ISSUE THREAD

**Issue by Detailocity** [MajorNibbles/AzureDevOpsTestConnectorPublic#1]
When syncing a SpecFlow feature file, the following error is encountered.

---------------------------
Microsoft Visual Studio
---------------------------
Unable to add steps to Test Plan, please check your settings 
Status Code:BadRequest(Hint: if 203 check your PAT settings!) 
Content Message:{"$id":"1","innerException":null,"message":"You must pass a valid patch document in the body of the request.","typeName":"Microsoft.VisualStudio.Services.Common.VssPropertyValidationException, Microsoft.VisualStudio.Services.Common","typeKey":"VssPropertyValidationException","errorCode":0,"eventId":3000}
---------------------------

The Test Suite was created, but not the test case.
NUnit tests are created correctly.

Visual Studio 16.3.7
Azure DevOps Server 2019 (Update 1)

**Comment by MajorNibbles** [comment]
Thanks, it looks like it's not identifying the steps correctly. Are there steps to the test you could share with me?

**Comment by Detailocity** [comment]
[SpecFlowFeatureFile.txt](https://github.com/MajorNibbles/AzureDevOpsTestConnectorPublic/files/3811331/SpecFlowFeatureFile.txt)

Here is a SpecFlow feature file that results in this error.

**Comment by MajorNibbles** [comment]
Thanks for the feature file. 

I've just released version 1.3.1 with the bug fix for this, and also another bug I discovered with updated test steps including the Test Attribute from the test beneath it. 

It should be downloadable in 5 minutes or so.

**Comment by Detailocity** [comment]
Yes, this did resolve the specific error.  Thank you.  I appreciate your responsiveness, which indicates you care.  So now I want to work with you to make this more effective, as I have a few more issues I'd like to cover.

**Comment by MajorNibbles** [comment]
Thanks for the update, please let me know any suggestions you have
