### ISSUE TITLE
Specflow Steps from Feature File not uploaded to Test Case in ADO

### ISSUE THREAD

**Issue by eliezercazares** [MajorNibbles/AzureDevOpsTestConnectorPublic#12]
Hello Major,

Loving the plugin. Thanks for your support and providing this way of validating the issue I am having.

Very much appreciated.

Issue is the Test Steps are not loaded into the Test Case in ADO. Everything else, like creating or updating a test suite, test plan and test case works fine, so I love it.

Feature File:
`@TestPlanId(123456)
@TestSuiteId(654321)

@UI
Feature: Bla Bla US #963852
As someone
I want to do something
So I can test it

@IE 
Scenario: My scenario description
Given actor has logged in
And actor navigates to the application
When the page title is this one
Then validate all formulary 1 input fields are displayed
And each of them work as expected in Spec 3.1 from BRD 1.3`

**Comment by eliezercazares** [comment]
Closed by accident. Reopened.

**Comment by MajorNibbles** [comment]
Hiya sorry it's taken so long to get back to this. By the looks of your example above you may of modified the tags you are using, I believe they are by default #TestPlanId() and #TestSuiteId(654321), before I start testing this can you please confirm what comments/tag settings you are using?

Guess also a quick question, I'm guessing the option to update specflow steps has been enabled in the options? :)

Thanks

**Comment by MajorNibbles** [comment]
Closing this as no answer to my questions, I will be happy to reopen with more information
