### ISSUE TITLE
When syncing Specflow tests to ADO the test case association isn't created correctly

### ISSUE THREAD

**Issue by cake-escape** [MajorNibbles/AzureDevOpsTestConnectorPublic#13]
When syncing tests from a specflow feature file into ADO the test case association doesn't seem to be getting created correctly in the "Associated Automation" tab.

For example, this is how the Associated Automation tab is currently populated by the connector:
![reference image 1](https://i.imgur.com/kOcJcWF.png)

And this is now it gets populated when manually selecting the "Associate to Test Case" option in VS:
![reference image 2](https://i.imgur.com/qhGDR9v.png)

This is a problem for us as it currently prevents the automated test in the linked test case from being run from ADO (it will display an error saying it can't the test in the linked dll, paraphrasing). So we have to manually create the linkage to the automation ourselves as per the second example.

**Comment by MajorNibbles** [comment]
Hi I have just released a new version which will hopefully resolve this issue, unfortunately my test set up isn't generating feature.cs files at the moment so can't check it my end, sorry. Could you please check and confirm?

**Comment by cake-escape** [comment]
Thank you for the speedy response.

We re-checked and it looks like there may still be a small issue with how the name of the test is getting cased when synced from VS. Although it does now include the fully qualified name, it looks like it also needs to be camel cased but is currently getting lower-cased. This seems to be affecting ADO from properly resolving it when run in a pipeline.

For example, as in the below:
![reference image 1](https://i.imgur.com/oqVbSG0.jpg)

And how it should look:
![reference image 2](https://i.imgur.com/qhGDR9v.png)

**Comment by MajorNibbles** [comment]
This should now be resolved, I'm still unable to test it for some reason...really sorry for the inconvenience but could you please check it for me?
