### ISSUE TITLE
Pascal or Camel case in feature or scenario name causes incorrect casing in association

### ISSUE THREAD

**Issue by BCRaveD** [MajorNibbles/AzureDevOpsTestConnectorPublic#14]
If the "Feature:" or "Scenario:" has Pascal or Camel case in the name, for example
```
Feature: TestTheUI
Scenario: The UI loads correctly
```
when linked the "Automated test name" will end with "Testtheui.TheUiLoadsCorrectly"
Whereas the test name from SpecFlow will retain the case and be "TestTheUI.TheUILoadsCorrectly"

When the feature name contains Pascal or Camel case, test cases in the feature do not report any outcome in the test run.
When only the scenario name(s) contains Pascal or Camel case, the test case(s), and subsequent test cases in the feature do not report any outcome in the test run (even if only some contain Pascal or Camel case).

**Comment by MajorNibbles** [comment]
Thank you, this feature has been very awkward to get right!
This research is great, I know what I need to do to fix this, and will release it soon

**Comment by BCRaveD** [comment]
Looks good.
Casing used in the scenario names is being retained in the linked test case name.
