### ISSUE TITLE
Steps containing symbols may not be synchronised

### ISSUE THREAD

**Issue by BCRaveD** [MajorNibbles/AzureDevOpsTestConnectorPublic#15]
We had a problem with one of our test cases synchronising with DevOps and identified that a specific step caused the problem.
The step contained a text string which includes some HTML code:
`And the HTML part contains "Some&nbsp;Text:&nbsp;My&nbsp;Text&nbsp;1"`

The test was created, but none of the test steps synchronised, and the test was not identified and run when a run was triggered from DevOps. No subsequent tests in the feature were identified and run either.

Once this step was removed in VS, the test case synchronised correctly.
I then added the step again but didn't re-synchronise (doing so at this point re-breaks the test in DevOps), and the test ran with all steps without issue, and subsequent tests in the feature were also identified and run.

**Comment by MajorNibbles** [comment]
This was an interesting one, & needs to be encoded to &amp;amp; for Azure DevOps to parse it...! Will be in the next release tonight

**Comment by MajorNibbles** [comment]
This has now been released, could you please confirm it's working your end?

**Comment by BCRaveD** [comment]
Looks good.
It created a new test case, and synchronised all the steps correctly.
There was already an existing test case from the previous sync which it didn't identify and update, even though the code has the appropriate #TestCaseReference(id). We can just deprecate that in DevOps.
The other test in the feature synchronised without creating duplicates.

Many thanks for a quick response!
