### ISSUE TITLE
Specflow Feature file Comments

### ISSUE THREAD

**Issue by Mormam** [MajorNibbles/AzureDevOpsTestConnectorPublic#2]
When selecting Comments insted of Attributes, it put **//** for comments insted **#**.

--Actual:

//TestCaseId(148)
**Scenario**: Extract Valid Date from Sdk 
**Given** I have access to sdk

--Should be:

#TestCaseId(148)
**Scenario**: Extract Valid Date from Sdk 
**Given** I have access to sdk

**Comment by MajorNibbles** [comment]
This has now been released in v1.3.2, thank you for the report
