### ISSUE TITLE
Visual studio 2022 support1

### ISSUE THREAD

**Issue by KotUW** [MajorNibbles/AzureDevOpsTestConnectorPublic#20]
If this is unmaintained, I can work on 2022 support. but will need source.

**Comment by MajorNibbles** [comment]
Hiya, after a bit of a hiatus from extension development to focus on a few other projects, I am contemplating redesigning this tool and releasing on VS2022. 
I've never run an opensource project on git before, but I think that'll be a good idea :)
I'll look into that and get back to you soon.

**Comment by KotUW** [comment]
Do you have an Idea on implementation details. And as I mentioned before source code of the original extension will be very helpful. Looking forward to be working on this with you.

**Comment by stevecollyer** [comment]
Any update on this?
We have been starting to use this extension, but everyone has now upgraded to vs2022.
There are other extension out there that do a job, but this is the best one we have found, so support for vs2022 would be very very welcome.

**Comment by MajorNibbles** [comment]
Hello all, finally got round to doing the VS2022 port...I had some issues but it's working now :) and it's....live!
I've also made the repo public!
https://github.com/MajorNibbles/ADOTestConnector64

Thank you for waiting, sorry it took me so long.
