### ISSUE TITLE
not working on VS 2022

### ISSUE THREAD

**Issue by ChandarJain** [MajorNibbles/AzureDevOpsTestConnectorPublic#21]
It's not working on visual studio 2022 can you tell me how can we get for 2022

**Comment by Naweap** [comment]
I think an upgrade should be made. It would also be very usefull in my case

**Comment by MajorNibbles** [comment]
Hello all, finally got round to doing the VS2022 port...I had some issues but it's working now :) and....live!
I've also made the repo public!
https://github.com/MajorNibbles/ADOTestConnector64

Thank you for waiting, sorry it took me so long.
