### ISSUE TITLE
Fail to Update test cases

### ISSUE THREAD

**Issue by Mormam** [MajorNibbles/AzureDevOpsTestConnectorPublic#4]
The test connector does not update the test cases in Devops.

**Comment by MajorNibbles** [comment]
Hiya, can you please provide an example file where this is the case?
Thanks

**Comment by Mormam** [comment]
> Hiya, can you please provide an example file where this is the case?
> Thanks

Hi,
I found the issue, the file must be saved before syncronize, Sorry My Bad
