### ISSUE TITLE
Replicate the test case for each line on example

### ISSUE THREAD

**Issue by Mormam** [MajorNibbles/AzureDevOpsTestConnectorPublic#5]
When use Examples: replicate the test case for each line on example using the value in example.

This way is not need to replicate the test case to associate the test automation

------------
Specflow Feature file:
Scenario Outline: Travel first class 
   Given I have access to the bus for _village_

Examples:
| _village_    |
| Lisbon    | 
| Oporto   | 

--------------------------------------------------------
DevOps Test Cases:
**Test Case 1**
_Title:_ Travel first class - Lisbon
_Steps:_ Given I have access to the bus for Lisbon

**Testcase 2**
_Title:_ Travel first class - Oporto
_Steps:_ Given I have access to the bus for Oporto

------------
_Possibility of connection_

Specflow Feature file:
Scenario Outline: Travel first class 
   Given I have access to the bus for <village>

Examples:
| village    |
| Lisbon    |  **#TestCaseId(1)**
| Oporto   |  **#TestCaseId(2)**

---------
Keep the good job

**Comment by MajorNibbles** [comment]
Hello, thanks for your suggestions and bugs, I'm planning to look into these in January, it's been a very busy couple of months!

**Comment by MajorNibbles** [comment]
Finally done! implemented in v1.5 :)
