### ISSUE TITLE
Tags in feature files are formatted as C# attribute

### ISSUE THREAD

**Issue by aurnoi1** [MajorNibbles/AzureDevOpsTestConnectorPublic#6]
Azure DevOps Test Connector build 1.3.2.
VS2019 Version 16.4.3
Deveroom 1.5.1 as Gherkin syntax highlighter. 

I have set the extension to generate attributes with the prefix @TestCase.
But the tags `(expected: @Testcase2980)` are formatted with extra bracket (actual: ` [@Testcase(2967)]` ) which is an invalid format for a feature file and the project won't build.

**Comment by MajorNibbles** [comment]
Thanks, this is a good suggestion, 
Version 1.3.3 has just been released. 
When using a specflow file with attributes rather than comments, the [ ] surrounds have been removed.
Please confirm your end!

**Comment by aurnoi1** [comment]
I confirm that build 1.3.3 has fixed the issue. Thanks a lot.
