### ISSUE TITLE
Enforced Brackets in Feature tags cause error for Specflow+LivinDoc

### ISSUE THREAD

**Issue by aurnoi1** [MajorNibbles/AzureDevOpsTestConnectorPublic#7]
Environment:
Azure DevOps Test Connector build 1.3.3.
VS2019 Version 16.4.3
Deveroom 1.5.1 as Gherkin syntax highlighter.

Problem:
When generating the tags for feature file, brackets are automatically add to encapsulate the Azure work item id. This is problematic when using Specflow+LivingDoc since it will parse the tag to retrieve the work item id and generate a link (LivingDoc expected a prefix followed by the work item id).

With the actual comportment the link generate by LivingDoc will be as '2346)' which will cause an error when click left on the link (strangely, right click and 'open link' works).

Even without LivingDoc, other parsing tools or custom script may be impacted as well, so the brackets should not be enforced.

Actual Result (where '@tm' is the prefix used in Test Connector and LivingDoc):
@tm(3051)

Expected Result:
@tm3051

**Comment by MajorNibbles** [comment]
I will be adding a fully customisable tag system in the next update, one for .cs files and one for .feature files. This will mean a user can type in exactly the format of the string they want the Id stored in.

**Comment by PawelMinuczyc-Stepstone** [comment]
Hey MajorNibbles,

This connector is great. How do you think, how long it will take to implement tags? We desperatly needs it. Do you need some help?

Greetings from Poland!

**Comment by MajorNibbles** [comment]
Hiya,
I'm in the middle of a large refactor of the code right now, once that has gone out I'll start looking at this.
I reckon it'll be done in the next couple of weeks. 

Sorry for the enormous delay! Time flies!

I am hoping to open up the code for people to contribute on it, I've not got much experience in open source things so I'll need to do some reading up on it...

**Comment by MajorNibbles** [comment]
Hello, I've just released a new version (v1.6.1) with attribute patterns :) in essence for your example you'd need to configure it the test case pattern to:

@tm~

you will need to be careful that the pattern doesn't match anything that isn't a Test case id :)

Please give it a go and let me know if this has resolved your issue.
