### ISSUE TITLE
Synchronize Scenario Outline example table with parameter values

### ISSUE THREAD

**Issue by aurnoi1** [MajorNibbles/AzureDevOpsTestConnectorPublic#9]
Hi,

When synchronizing a Scenario Outline the table Example is not included in the test case. This should be implemented by adding the example table value as parameter values in the TestCase.

A transformation is required at step level since the placeholder are formatted as <placeholder> in feature file but @placeholder in TestCase.

An example could be the [SpecSync implementation](https://specsolutions.gitbook.io/specsync/important-concepts/synchronizing-scenario-outlines).

Thanks.

**Comment by MajorNibbles** [comment]
Implemented in v1.5 :)
